

services:
  db:
    image: bitnami/postgresql:17.4.0
    platform: linux/amd64
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - docker-fastapi-base
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@db:5432/${POSTGRESQL_DATABASE}
    env_file:
      - .env.production
    networks:
      - docker-fastapi-base
    restart: unless-stopped
    volumes:
      - .:/app  # For development - remove this for production
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # --reload for development

volumes:
  db-data:

networks:
  docker-fastapi-base:
    driver: bridge
