databases:
  - name: taskify-db
    databaseName: taskify
    user: taskify_user
    plan: free

services:
  - type: web
    name: taskify-backend
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      # API Settings
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: Taskify
      - key: FRONTEND_URL
        value: https://taskify-seven-iota.vercel.app/
      
      # Security Settings
      - key: JWT_SECRET_KEY
        value: ABSaCK8n-kLk53tPtQ2j8l1DpToegzhie6wa89CFV40
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: ALGORITHM
        value: HS256
      
      # CORS Settings
      - key: BACKEND_CORS_ORIGINS
        value: https://taskify-seven-iota.vercel.app,http://localhost:3000,http://localhost:5173
      
      # Database Settings
      - key: POSTGRESQL_SERVER
        fromDatabase:
          name: taskify-db
          property: host
      - key: POSTGRESQL_USERNAME
        fromDatabase:
          name: taskify-db
          property: user
      - key: POSTGRESQL_PASSWORD
        fromDatabase:
          name: taskify-db
          property: password
      - key: POSTGRESQL_DATABASE
        fromDatabase:
          name: taskify-db
          property: database
      - key: POSTGRESQL_PORT
        fromDatabase:
          name: taskify-db
          property: port
      
      # Domain Settings
      - key: DOMAIN
        value: taskify-backend.onrender.com
      - key: ENVIRONMENT
        value: production
      
      # Email Settings
      - key: EMAIL_ENABLED
        value: "true"
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: jonazkeez@gmail.com
      - key: SMTP_PASSWORD
        value: gfea eftt jxmr zoww
      - key: SMTP_SENDER_EMAIL
        value: jonazkeez@gmail.com
