"""Add password reset codes table

Revision ID: 06d0fa17601d
Revises: 7bd6d22d41f7
Create Date: 2025-06-03 22:49:00.291703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d0fa17601d'
down_revision: Union[str, None] = '7bd6d22d41f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
