"""fix_project_role_enum_values

Revision ID: aa9a3f66164a
Revises: c61e1b00feb4
Create Date: 2025-06-11 02:55:00.262744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9a3f66164a'
down_revision: Union[str, None] = 'c61e1b00feb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
