"""Add deadline field to projects table

Revision ID: aacf3da8d0b3
Revises: 7acfde57b1ab
Create Date: 2025-06-17 09:45:12.057167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacf3da8d0b3'
down_revision: Union[str, None] = '7acfde57b1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deadline')
    # ### end Alembic commands ###
